name: ci
on:
  pull_request:
    types:
      - opened
      - closed
  workflow_dispatch:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: chcekout code
        uses: actions/checkout@v4.2.2
      - name: npm build
        run: npm ci

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps: 
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: build dockerfile
        run: echo "dockerfile"
       
